# Generated by Django 5.0.7 on 2024-07-17 23:15

import article.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=50000)),
                ('image', models.ImageField(upload_to=article.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date uploaded')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
