# Generated by Django 5.0.7 on 2024-07-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('marathon', models.TextField(max_length=400)),
                ('topic', models.CharField(choices=[('Tash', 'Tashkent'), ('Buk', 'Bukhara'), ('And', 'Andijan')], max_length=5)),
            ],
            options={
                'verbose_name': 'The Marathon',
                'verbose_name_plural': 'Marathons',
            },
        ),
    ]
